"""Deterministic Stress Testing and Scenario Analysis Engine for Institutional Treasuries.

DISCLAIMER: HACKATHON SIMULATION ENGINE - NOT A FORECASTING MODEL
The scenarios, shocks, and simulated portfolio impacts generated by this engine
are deterministic, illustrative stress assumptions designed for capital adequacy
and policy compliance testing under adverse tail conditions. They DO NOT represent
predictive market forecasts, economic certainties, or audited regulatory stress tests.
"""
from typing import Dict, List, Optional
import numpy as np
import pandas as pd

from app.engine.analytics import validate_weights
from app.engine.risk_controller import RiskControlEngine
from app.schemas.portfolio import (
    Asset,
    AssetClass,
    AssetStressImpact,
    DefensiveRebalanceResult,
    MultiScenarioComparison,
    PolicyEvaluation,
    PortfolioConfig,
    RiskState,
    ScenarioSummary,
    StressScenario,
    StressTestResult,
    TreasuryPolicy,
)


def get_predefined_scenarios() -> Dict[str, StressScenario]:
    """Provides standard institutional macroeconomic stress scenarios.

    Scenarios:
    1. EQUITY_CRASH: Severe decline in equities/strategic yield with modest credit contagion.
    2. INTEREST_RATE_SHOCK: Sharp yield curve spike hitting fixed-income durations.
    3. LIQUIDITY_CRISIS: Flight to cash and T-bills, illiquidity discounts on credit and yield buffers.
    4. INFLATION_SHOCK: Stagflationary impulse eroding fixed income, while commodities/hedges rally.
    5. COMBINED_MACRO_SHOCK: Synchronized macroeconomic crisis across equities, rates, and credit.
    """
    return {
        "EQUITY_CRASH": StressScenario(
            scenario_id="EQUITY_CRASH",
            name="Global Equity & Strategic Yield Crash",
            description="Severe 25% drop in equities and strategic yield buffers with minor corporate spread widening.",
            asset_class_shocks={
                AssetClass.CASH_EQUIVALENTS.value: 0.000,
                AssetClass.SOVEREIGN_BONDS.value: +0.005,      # Flight-to-safety duration rally
                AssetClass.COMMERCIAL_PAPER.value: -0.010,
                AssetClass.CORPORATE_BONDS.value: -0.050,      # Credit spread widening
                AssetClass.STRATEGIC_YIELD.value: -0.250,      # Severe equity/hedge drawdown
            },
            severity="SEVERE",
            assumptions="Flight to quality preserves sovereign paper and cash; equity risk premia spike.",
        ),
        "INTEREST_RATE_SHOCK": StressScenario(
            scenario_id="INTEREST_RATE_SHOCK",
            name="Parallel Interest Rate Surge (+150 bps)",
            description="Sharp upward rate shock causing duration-driven capital losses in fixed-income portfolios.",
            asset_class_shocks={
                AssetClass.CASH_EQUIVALENTS.value: +0.002,     # Higher overnight reinvestment yield
                AssetClass.SOVEREIGN_BONDS.value: -0.060,      # Duration drag on 3M-5Y sovereigns
                AssetClass.COMMERCIAL_PAPER.value: -0.015,     # Modest short-duration drag
                AssetClass.CORPORATE_BONDS.value: -0.085,      # Rate rise + credit spread decompression
                AssetClass.STRATEGIC_YIELD.value: -0.040,      # Multiple compression
            },
            severity="MODERATE",
            assumptions="Yield curve shifts upward in parallel; cash benefits from rate resets.",
        ),
        "LIQUIDITY_CRISIS": StressScenario(
            scenario_id="LIQUIDITY_CRISIS",
            name="Institutional Liquidity Squeeze & Credit Freeze",
            description="Market freeze in corporate credit and illiquid yield buffers; cash remains liquid.",
            asset_class_shocks={
                AssetClass.CASH_EQUIVALENTS.value: 0.000,      # Full liquidity preservation
                AssetClass.SOVEREIGN_BONDS.value: -0.005,      # Slight market depth strain
                AssetClass.COMMERCIAL_PAPER.value: -0.045,     # Non-bank issuance freeze
                AssetClass.CORPORATE_BONDS.value: -0.100,      # Illiquid secondary bond market discounts
                AssetClass.STRATEGIC_YIELD.value: -0.180,      # Heavy fire-sale haircuts
            },
            severity="SEVERE",
            assumptions="Secondary dealer liquidity evaporates for corporate credit; Tier 1 cash is paramount.",
        ),
        "INFLATION_SHOCK": StressScenario(
            scenario_id="INFLATION_SHOCK",
            name="Unanchored Inflation & Commodity Spike",
            description="Stagflationary impulse punishing fixed income while real commodity buffers hedge.",
            asset_class_shocks={
                AssetClass.CASH_EQUIVALENTS.value: -0.010,     # Purchasing power drag / negative real return
                AssetClass.SOVEREIGN_BONDS.value: -0.070,      # High inflation discount on nominal bonds
                AssetClass.COMMERCIAL_PAPER.value: -0.020,     # Inflation discount
                AssetClass.CORPORATE_BONDS.value: -0.090,      # Input cost pressure on corporate balance sheets
                AssetClass.STRATEGIC_YIELD.value: +0.060,      # Commodity / inflation overlay appreciation
            },
            severity="MODERATE",
            assumptions="Real assets and inflation overlays appreciate; nominal bonds suffer severe duration losses.",
        ),
        "COMBINED_MACRO_SHOCK": StressScenario(
            scenario_id="COMBINED_MACRO_SHOCK",
            name="Severe Synchronized Macroeconomic Crisis",
            description="Simultaneous equity crash, sovereign duration loss, and corporate credit freeze.",
            asset_class_shocks={
                AssetClass.CASH_EQUIVALENTS.value: 0.000,
                AssetClass.SOVEREIGN_BONDS.value: -0.045,
                AssetClass.COMMERCIAL_PAPER.value: -0.050,
                AssetClass.CORPORATE_BONDS.value: -0.120,
                AssetClass.STRATEGIC_YIELD.value: -0.220,
            },
            severity="EXTREME",
            assumptions="Worst-case tail event combining liquidity freeze, rate spike, and equity rout.",
        ),
    }


class StressTestingEngine:
    """Evaluates portfolio capital adequacy and policy compliance under deterministic stress scenarios."""

    def __init__(
        self,
        risk_controller: Optional[RiskControlEngine] = None,
        periods_per_year: int = 252,
    ) -> None:
        """Initializes the stress testing engine."""
        self.periods_per_year = periods_per_year
        self.risk_controller = risk_controller or RiskControlEngine(periods_per_year=periods_per_year)

    def validate_scenario(self, scenario: StressScenario) -> None:
        """Validates scenario parameters for numerical consistency and domain boundaries.

        Raises
        ------
        ValueError
            If scenario IDs, shock values, or ranges are malformed.
        """
        if not scenario.scenario_id or not isinstance(scenario.scenario_id, str):
            raise ValueError("Scenario scenario_id must be a non-empty string.")
        if not scenario.name or not isinstance(scenario.name, str):
            raise ValueError("Scenario name must be a non-empty string.")
        if not scenario.asset_class_shocks and not scenario.symbol_shocks:
            raise ValueError("Scenario must specify at least one asset class shock or symbol shock.")

        # Validate numeric ranges
        for ac, shock in scenario.asset_class_shocks.items():
            if not isinstance(shock, (int, float)) or np.isnan(shock) or np.isinf(shock):
                raise ValueError(f"Invalid shock value for asset class '{ac}': {shock}")
            if shock <= -1.0:
                raise ValueError(
                    f"Shock for asset class '{ac}' is {shock:.2%}. "
                    "Long-only assets cannot lose 100% or more of capital (must be > -1.0)."
                )
            if shock > 2.0:
                raise ValueError(f"Shock for asset class '{ac}' is {shock:.2%}, exceeding realistic upper bound (+200%).")

        for sym, shock in scenario.symbol_shocks.items():
            if not isinstance(shock, (int, float)) or np.isnan(shock) or np.isinf(shock):
                raise ValueError(f"Invalid shock value for symbol '{sym}': {shock}")
            if shock <= -1.0:
                raise ValueError(f"Shock for symbol '{sym}' is {shock:.2%}, which violates lower bound (> -1.0).")
            if shock > 2.0:
                raise ValueError(f"Shock for symbol '{sym}' exceeds realistic upper bound (+200%).")

    def resolve_asset_shock(self, asset: Asset, scenario: StressScenario) -> float:
        """Resolves the percentage shock applicable to a specific asset under a scenario.

        Hierarchy:
        1. Exact symbol override in scenario.symbol_shocks
        2. Exact asset class match in scenario.asset_class_shocks
        3. Case-insensitive / substring match in scenario.asset_class_shocks
        4. Default: 0.0 (no shock)
        """
        if asset.symbol in scenario.symbol_shocks:
            return float(scenario.symbol_shocks[asset.symbol])

        if asset.asset_class in scenario.asset_class_shocks:
            return float(scenario.asset_class_shocks[asset.asset_class])

        # Substring / case-insensitive fallback
        asset_class_lower = asset.asset_class.lower()
        for ac, shock in scenario.asset_class_shocks.items():
            if ac.lower() in asset_class_lower or asset_class_lower in ac.lower():
                return float(shock)

        return 0.0

    def run_stress_test(
        self,
        portfolio_weights: Dict[str, float],
        assets: List[Asset],
        scenario: StressScenario,
        historical_returns: pd.DataFrame,
        policy: Optional[TreasuryPolicy] = None,
        total_capital: float = 10_000_000.0,
        trigger_defensive_on_breach: bool = True,
    ) -> StressTestResult:
        """Executes a single deterministic stress scenario simulation on a portfolio.

        Parameters
        ----------
        portfolio_weights : Dict[str, float]
            Baseline portfolio weights (sum to 1.0).
        assets : List[Asset]
            List of institutional instruments.
        scenario : StressScenario
            Deterministic scenario definition with shocks.
        historical_returns : pd.DataFrame
            Historical daily returns for risk and policy evaluation.
        policy : Optional[TreasuryPolicy]
            Treasury policy rules.
        total_capital : float
            Current fund / treasury capital.
        trigger_defensive_on_breach : bool
            If True, automatically triggers Phase 3 defensive rebalancer when stress results
            in BREACH or CRITICAL policy status.

        Returns
        -------
        StressTestResult
            Stressed returns, monetary P&L, per-asset contributions, post-shock weights,
            policy status, and optional defensive rebalance recommendation.
        """
        validate_weights(portfolio_weights, allowed_symbols=[a.symbol for a in assets])
        self.validate_scenario(scenario)

        if total_capital <= 0:
            raise ValueError(f"total_capital must be strictly positive, got {total_capital}")

        pol = policy or TreasuryPolicy()
        symbols = [a.symbol for a in assets]

        # 1. Calculate per-asset stress shocks & contributions
        asset_impacts: List[AssetStressImpact] = []
        stressed_p_return = 0.0
        post_shock_dollar_values: Dict[str, float] = {}

        for a in assets:
            w_init = portfolio_weights.get(a.symbol, 0.0)
            shock = self.resolve_asset_shock(a, scenario)
            contrib_ret = w_init * shock
            contrib_pnl = total_capital * contrib_ret
            stressed_val = total_capital * w_init * (1.0 + shock)

            stressed_p_return += contrib_ret
            post_shock_dollar_values[a.symbol] = stressed_val

            asset_impacts.append(AssetStressImpact(
                symbol=a.symbol,
                asset_class=a.asset_class,
                initial_weight=w_init,
                applied_shock=shock,
                contribution_return=contrib_ret,
                contribution_pnl=contrib_pnl,
                stressed_value=stressed_val,
                stressed_weight=0.0,  # Populated after total stressed capital is computed
            ))

        # 2. Portfolio-Level Stressed Values
        stressed_pnl = total_capital * stressed_p_return
        stressed_portfolio_val = total_capital + stressed_pnl

        # 3. Post-Shock Drifting Weights
        stressed_weights: Dict[str, float] = {}
        if stressed_portfolio_val > 0:
            for impact in asset_impacts:
                w_stressed = impact.stressed_value / stressed_portfolio_val
                impact.stressed_weight = w_stressed
                stressed_weights[impact.symbol] = w_stressed
        else:
            # Complete capital wipeout edge-case
            for impact in asset_impacts:
                impact.stressed_weight = impact.initial_weight
                stressed_weights[impact.symbol] = impact.initial_weight

        # 4. Post-Shock Metrics & Policy Control Evaluation
        stressed_metrics = self.risk_controller._compute_portfolio_metrics(
            stressed_weights, assets, historical_returns, pol.cvar_confidence_level
        )
        policy_eval = self.risk_controller.evaluate_policy(
            stressed_weights, assets, stressed_metrics, pol
        )

        # Baseline expected return for comparison
        baseline_metrics = self.risk_controller._compute_portfolio_metrics(
            portfolio_weights, assets, historical_returns, pol.cvar_confidence_level
        )

        # 5. Defensive Rebalancing Response (if breached)
        defensive_resp: Optional[DefensiveRebalanceResult] = None
        if trigger_defensive_on_breach and policy_eval.requires_rebalance:
            defensive_resp = self.risk_controller.execute_defensive_rebalance(
                current_weights=stressed_weights,
                assets=assets,
                historical_returns=historical_returns,
                policy=pol,
                total_capital=max(1.0, stressed_portfolio_val),
            )

        # 6. Restored State Evaluation (preserving trigger semantics)
        if defensive_resp is not None and defensive_resp.status == "SUCCESS":
            restored_portfolio_val = defensive_resp.post_rebalance_capital
            restored_cvar = defensive_resp.defensive_metrics.get("cvar_95")
            restored_liq = defensive_resp.defensive_metrics.get("liquidity_score")
            restored_status = (
                defensive_resp.post_rebalance_policy.overall_status
                if defensive_resp.post_rebalance_policy
                else "NORMAL"
            )
        else:
            restored_portfolio_val = stressed_portfolio_val
            restored_cvar = stressed_metrics.cvar_95_historical
            restored_liq = stressed_metrics.weighted_liquidity_score
            restored_status = policy_eval.overall_status

        # 7. Structured Narrative Summary
        summary = (
            f"Scenario '{scenario.name}' ({scenario.severity}): Stressed return of {stressed_p_return:+.2%}, "
            f"resulting in net P&L of ${stressed_pnl:,.2f}. Ending capital: ${stressed_portfolio_val:,.2f}. "
            f"Policy Status: {policy_eval.overall_status} ({len(policy_eval.breached_checks)} breach(es))."
        )

        return StressTestResult(
            scenario_id=scenario.scenario_id,
            scenario_name=scenario.name,
            severity=scenario.severity,
            base_portfolio_return=baseline_metrics.expected_return_annualized,
            base_portfolio_value=total_capital,
            stressed_portfolio_return=stressed_p_return,
            stressed_pnl=stressed_pnl,
            stressed_portfolio_value=stressed_portfolio_val,
            asset_impacts=asset_impacts,
            stressed_weights=stressed_weights,
            policy_status=policy_eval.overall_status,
            breached_constraints=policy_eval.breached_checks,
            policy_evaluation=policy_eval,
            defensive_response=defensive_resp,
            summary=summary,
            restored_portfolio_value=restored_portfolio_val,
            restored_cvar=restored_cvar,
            restored_liquidity=restored_liq,
            restored_status=restored_status,
            base_cvar=baseline_metrics.cvar_95_historical,
            base_liquidity=baseline_metrics.weighted_liquidity_score,
            stressed_cvar=stressed_metrics.cvar_95_historical,
            stressed_liquidity=stressed_metrics.weighted_liquidity_score,
        )

    def run_multi_scenario_comparison(
        self,
        portfolio_weights: Dict[str, float],
        assets: List[Asset],
        historical_returns: pd.DataFrame,
        scenarios: Optional[List[StressScenario]] = None,
        policy: Optional[TreasuryPolicy] = None,
        total_capital: float = 10_000_000.0,
    ) -> MultiScenarioComparison:
        """Executes a comparative battery of stress tests across multiple scenarios.

        Parameters
        ----------
        portfolio_weights : Dict[str, float]
            Current portfolio allocation.
        assets : List[Asset]
            Available assets universe.
        historical_returns : pd.DataFrame
            Historical daily returns.
        scenarios : Optional[List[StressScenario]]
            Scenarios to evaluate. Defaults to all 5 standard institutional scenarios.
        policy : Optional[TreasuryPolicy]
            Treasury policy rules.
        total_capital : float
            Portfolio capital pool.

        Returns
        -------
        MultiScenarioComparison
            Summary matrix and detailed stress test results.
        """
        scenario_list = scenarios or list(get_predefined_scenarios().values())
        detailed_results: Dict[str, StressTestResult] = {}
        summaries: List[ScenarioSummary] = []

        baseline_metrics = self.risk_controller._compute_portfolio_metrics(
            portfolio_weights, assets, historical_returns, 0.95
        )

        for sc in scenario_list:
            res = self.run_stress_test(
                portfolio_weights=portfolio_weights,
                assets=assets,
                scenario=sc,
                historical_returns=historical_returns,
                policy=policy,
                total_capital=total_capital,
                trigger_defensive_on_breach=True,
            )
            detailed_results[sc.scenario_id] = res
            summaries.append(ScenarioSummary(
                scenario_id=sc.scenario_id,
                scenario_name=sc.name,
                severity=sc.severity,
                stressed_return=res.stressed_portfolio_return,
                stressed_pnl=res.stressed_pnl,
                stressed_value=res.stressed_portfolio_value,
                policy_status=res.policy_status,
                num_breached_policies=len(res.breached_constraints),
                breached_policies=res.breached_constraints,
                restored_value=res.restored_portfolio_value,
            ))

        return MultiScenarioComparison(
            base_capital=total_capital,
            base_return=baseline_metrics.expected_return_annualized,
            scenarios=summaries,
            detailed_results=detailed_results,
        )
