"""Deterministic Synthetic Historical Return Generator for Institutional Treasury Assets.

================================================================================
DISCLAIMER: DEMO / SYNTHETIC DATA
The data generated by this module is purely synthetic, generated via deterministic
pseudo-random processes with fixed seeds. It is intended solely for algorithmic
testing, interface validation, and platform demonstration. It DOES NOT represent
live market prices, real financial advice, or verified audited quotes.
================================================================================
"""
from typing import List, Optional
import numpy as np
import pandas as pd

from backend.app.schemas.portfolio import Asset, AssetClass, LiquidityTier

# Prominently exported banner
DATA_DISCLAIMER = "DEMO / SYNTHETIC DATA - NOT LIVE MARKET QUOTES"

# Standard institutional demo asset universe
DEFAULT_INSTITUTIONAL_ASSETS: List[Asset] = [
    Asset(
        symbol="USD_CASH",
        name="USD Overnight Treasury Cash & Repo",
        asset_class=AssetClass.CASH_EQUIVALENTS.value,
        liquidity_tier=LiquidityTier.TIER_1_IMMEDIATE.value,
        liquidity_score=1.0,
        duration=0.0,
        expected_return=0.045,
    ),
    Asset(
        symbol="US_TBILL_3M",
        name="US 3-Month Treasury Bills",
        asset_class=AssetClass.SOVEREIGN_BONDS.value,
        liquidity_tier=LiquidityTier.TIER_2_OPERATIONAL.value,
        liquidity_score=0.95,
        duration=0.25,
        expected_return=0.048,
    ),
    Asset(
        symbol="COMM_PAPER_30D",
        name="Tier-1 30-Day Commercial Paper",
        asset_class=AssetClass.COMMERCIAL_PAPER.value,
        liquidity_tier=LiquidityTier.TIER_2_OPERATIONAL.value,
        liquidity_score=0.85,
        duration=0.08,
        expected_return=0.052,
    ),
    Asset(
        symbol="US_CORP_IG",
        name="US Investment Grade Corporate Bond Fund",
        asset_class=AssetClass.CORPORATE_BONDS.value,
        liquidity_tier=LiquidityTier.TIER_3_STRATEGIC.value,
        liquidity_score=0.65,
        duration=3.5,
        expected_return=0.058,
    ),
    Asset(
        symbol="STRAT_YIELD_BUF",
        name="Strategic Yield & Hedged Overlay Buffer",
        asset_class=AssetClass.STRATEGIC_YIELD.value,
        liquidity_tier=LiquidityTier.TIER_3_STRATEGIC.value,
        liquidity_score=0.40,
        duration=1.2,
        expected_return=0.070,
    ),
]


def generate_deterministic_synthetic_returns(
    assets: Optional[List[Asset]] = None,
    n_periods: int = 252,
    seed: int = 42,
) -> pd.DataFrame:
    """Generates deterministic daily synthetic returns for testing and demonstration.

    Features:
    - Fixed RNG seed guarantees 100% reproducible results across test runs.
    - Explicit correlation structure (e.g. flight-to-safety sovereign bonds vs corporate paper).
    - Preserves realistic treasury risk characteristics (low vol for cash/T-bills, fat tail shocks for yield assets).

    Parameters
    ----------
    assets : Optional[List[Asset]]
        Asset universe to generate returns for. Defaults to DEFAULT_INSTITUTIONAL_ASSETS.
    n_periods : int
        Number of trading days (default 252 for 1 financial year).
    seed : int
        RNG seed ensuring determinism (default 42).

    Returns
    -------
    pd.DataFrame
        DataFrame with shape (n_periods, n_assets) containing daily percentage returns,
        indexed by trading day integer (0 to n_periods-1). Columns are asset symbols.
    """
    if assets is None:
        assets = DEFAULT_INSTITUTIONAL_ASSETS

    n_assets = len(assets)
    symbols = [a.symbol for a in assets]

    rng = np.random.default_rng(seed)

    # Base daily parameters (annualized mean / 252, annualized vol / sqrt(252))
    # Target annualized profiles:
    # Cash: ret=4.5%, vol=0.2%
    # T-Bill: ret=4.8%, vol=0.6%
    # CP: ret=5.2%, vol=1.4%
    # Corp IG: ret=5.8%, vol=5.0%
    # Strategic Yield: ret=7.0%, vol=10.0%
    annual_vols = []
    annual_means = []

    for a in assets:
        ann_ret = a.expected_return if a.expected_return is not None else 0.05
        annual_means.append(ann_ret)
        if "CASH" in a.symbol:
            annual_vols.append(0.002)
        elif "TBILL" in a.symbol or "SOV" in a.symbol:
            annual_vols.append(0.006)
        elif "PAPER" in a.symbol or "CP" in a.symbol:
            annual_vols.append(0.014)
        elif "CORP" in a.symbol:
            annual_vols.append(0.050)
        else:
            annual_vols.append(0.100)

    daily_means = np.array(annual_means) / 252.0
    daily_vols = np.array(annual_vols) / np.sqrt(252.0)

    # Correlation matrix:
    # Cash has near-zero correlation with all
    # T-Bill and Corp have modest correlation
    # Corp and Strategic Yield have positive correlation (0.45)
    # T-Bill and Strategic Yield have negative/flight-to-quality correlation (-0.15)
    corr_matrix = np.eye(n_assets)
    for i in range(n_assets):
        for j in range(i + 1, n_assets):
            sym_i, sym_j = symbols[i], symbols[j]
            if "CASH" in sym_i or "CASH" in sym_j:
                c = 0.02
            elif ("TBILL" in sym_i and "CORP" in sym_j) or ("CORP" in sym_i and "TBILL" in sym_j):
                c = 0.20
            elif ("TBILL" in sym_i and "STRAT" in sym_j) or ("STRAT" in sym_i and "TBILL" in sym_j):
                c = -0.15  # Flight to quality
            elif ("CORP" in sym_i and "STRAT" in sym_j) or ("STRAT" in sym_i and "CORP" in sym_j):
                c = 0.45   # Credit/market risk correlation
            else:
                c = 0.15
            corr_matrix[i, j] = c
            corr_matrix[j, i] = c

    # Construct covariance matrix: Cov = diag(vol) * Corr * diag(vol)
    cov_matrix = np.outer(daily_vols, daily_vols) * corr_matrix

    # Generate correlated normal samples
    raw_returns = rng.multivariate_normal(mean=daily_means, cov=cov_matrix, size=n_periods)

    # Introduce a deterministic downside liquidity/credit stress shock at day 120 and day 180
    # to demonstrate tail risk, downside diversification, and drawdown
    if n_periods > 180:
        for idx, a in enumerate(assets):
            if "CORP" in a.symbol:
                raw_returns[120, idx] -= 0.018  # -1.8% credit widening shock
                raw_returns[180, idx] -= 0.022  # -2.2% downgrade event
            elif "STRAT" in a.symbol:
                raw_returns[120, idx] -= 0.035  # -3.5% liquidity draw
                raw_returns[180, idx] -= 0.045  # -4.5% market shock
            elif "TBILL" in a.symbol:
                raw_returns[120, idx] += 0.003  # Flight to safety bond price rise
                raw_returns[180, idx] += 0.004

    df = pd.DataFrame(raw_returns, columns=symbols)
    df.attrs["description"] = DATA_DISCLAIMER
    df.attrs["seed"] = seed
    df.attrs["is_synthetic"] = True
    return df
